  
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

stages:
- stage: A
  jobs:
  - job: A1
    pool:
      vmImage: latest
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: "echo ''Hello world''"
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''
          noProfile: false
          noRc: false
      
- stage: B
  jobs:
  - job: A2
    pool: server
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 2
        inputs:
          notifyUsers: 'abnaraya@microsoft.com'
          instructions: 'check output in logs'
          onTimeout: reject
