  
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

stages:
- stage: A
  jobs:
  - job: A1
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'

- stage: B
  jobs:
  - job: A2
    pool: server
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 2
        inputs:
          notifyUsers: 'abnaraya@microsoft.com'
          instructions: 'check output in logs'
          onTimeout: reject
